finished week 3 assessment
learn-academy-2022-alpha/week-3-assessment-CarRamos pull request #1
Opened 2022-03-07 07:03 UTC by CarRamos

2022-03-07 15:43 UTC, SunkissedQueen requested changes
Carlos, your code and test look great. Please add jest and run your test suite on the code-challenges.test.js file. Then post the results. Please start adding more of your experience on the interview questions, especially if you are not quite sure about the answer.

2022-03-07 15:43 UTC, SunkissedQueen commented on code-challenges.test.js
> +const { result } = require("lodash")
This is helper code from your text editor. it is called yargs. If you get errors that state you don't have a test in your test suite, then definitely look to see if you save and look at the top of your file for code like on Lines 3-5, comment it out and you should be able to test out the info.

2022-03-07 15:43 UTC, SunkissedQueen commented on code-challenges.test.js
> +
Great setup. Please install jest and run the test suites. Then place the results of the test suite for the test and then the function. After you comment out the helper code that your text editor VScode added, you should be able to.

2022-03-07 15:43 UTC, SunkissedQueen commented on code-challenges.test.js
> +const fibSqu = (number) => {
So clean. Indentation looks great.

2022-03-07 15:43 UTC, SunkissedQueen commented on code-challenges.test.js
>  const fullArr1 = [4, 9, 0, "7", 8, true, "hey", 7, 199, -9, false, "hola"]
Because you have already placed the variables in your test, you don't need to declare them again. The test suite will keep track of them.

2022-03-07 15:43 UTC, SunkissedQueen commented on code-challenges.test.js
> +function sumOfAll (array) {
Great approach. I bet you can do this with one return statement without  a variable.

2022-03-07 15:43 UTC, SunkissedQueen commented on interview-questions.md
> +  Researched answer: after some research, im even more confused
Yes, `this` is special. But in general, it is a keyword. You cannot change the value of `this`. In JavaScript, the `this` keyword refers to an object. Checkout w3schools for an explanation. https://www.w3schools.com/js/js_this.asp

2022-03-07 15:43 UTC, SunkissedQueen commented on interview-questions.md
> +  Researched answer: Yarn is a package manager. I dont understand that last part.
Recall when with use yarn commands how several files were added to your projects. Yarn  adds all the necessary code snippets and software to get projects running. It's kind of like someone providing all the DJ equipment, power, stage, everything setup and ready to go, then all you have to bring is your energy and skills to party. Yarn controls the package that is code/software necessary for your project so you don't have to go research and download over 15,000 pieces of code to get rolling. Thank you to whoever took the time to group that stuff.

2022-03-07 15:43 UTC, SunkissedQueen commented on interview-questions.md
For your interview questions, please add more of your experience with the answers. For instance, I recall when I explored the use of the keyword `this`. Tell the story of one of the challenges. Tell your thoughts as well as what you researched. These interview questions are opportunities to practice sharing your thoughts with an interviewer/future clients.

2022-03-07 15:43 UTC, SunkissedQueen commented on react-debugging.html
> +            <>
Yes, following the prompts from the console definitely gets you to the solution quicker. Great job!

2022-03-08 00:32 UTC, CarRamos commented
> Carlos, your code and test look great. Please add jest and run your test suite on the code-challenges.test.js file. Then post the results. Please start adding more of your experience on the interview questions, especially if you are not quite sure about the answer.

how do i post the results? i have the test on there

2022-03-08 18:10 UTC, SunkissedQueen approved these changes
Thank you for clarifying that you did not push the jest file but did run your test suites. Carlos, you are approved! If there are any questions on the expectation for next assessment, please reach out.

2022-03-18 22:18 UTC, merged